alias a='ls -lrthG'
alias ga='git add .'
alias gd='git diff --color=always'
alias gs='git status'
alias gc='git commit -am'
alias gpom='git push origin master'
alias pr='powder restart'
alias retag='/usr/local/bin/ctags -R --exclude=.git --exclude=log --exclude=tmp *'
alias t='rvm 2.1@tmux && tmuxinator'
alias u='cd ..'
alias vi='mvim -v'
alias vim='mvim -v'

EDITOR='vim'
PATH=/usr/local/bin:$PATH
